# Generated by Django 2.2.4 on 2019-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_auto_20190927_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post2model',
            options={'verbose_name': 'post2', 'verbose_name_plural': 'posts2'},
        ),
        migrations.AddField(
            model_name='post2model',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('private', 'Private')], default='publish', max_length=120),
        ),
    ]
