# Generated by Django 2.2.4 on 2019-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_auto_20191001_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2model',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True),
        ),
    ]
