# Generated by Django 2.2.4 on 2019-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0005_post2model_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2model',
            name='title',
            field=models.CharField(error_messages={'blank': 'This field is not full pelase. give some title.', 'null': 'This field is not full pelase. give some title.', 'unique': 'This title is not unique, please try again.'}, max_length=240),
        ),
    ]
