# Generated by Django 2.2.4 on 2019-10-01 07:49

import blog2.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0008_auto_20191001_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2model',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[blog2.custom_validators.validate_school_email]),
        ),
    ]
