# Generated by Django 2.2.4 on 2019-10-01 07:51

import blog2.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0009_auto_20191001_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2model',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog2.custom_validators.validate_school_email, blog2.custom_validators.validate_author_email]),
        ),
    ]
