# Generated by Django 2.2.4 on 2019-10-01 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0010_auto_20191001_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2model',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post2model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
